### ISSUE TITLE
add links to etherscan / polyscan after create / write

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/js-tableland-cli#14]
the CLI currently reposts the `hash` of the transactions, but it's not super clear what this hash is... we could call it `txn` or better yet, include links to the txn on etherscan / optimism.ethersan / polyscan.

**Comment by carsonfarmer** [comment]
Yeh I like this suggestion. I think we should change the response key in the SDK (and maybe on the response from the API?) from `hash` to `txn` as suggested by @sanderpick. I think an audit here might be nice, because IIRC, we _do_ call it `txn_hash` elsewhere? Or perhaps that's what ethersjs calls it? We should try to match that.

Additionally, I think including the *scan link is a nice feature to have. I'll sneak this into a future PR.

**Comment by joewagner** [comment]
When the SDK goes direct to the contract ethers.js returns `{transactionHash: <hashvalue>}`, the Validator RPC returns `{tx: {hash: <hashvalue>}}`.  
Maybe the SDK could pass along the return value from ethers, and map the RCP result to match ethers?

**Comment by carsonfarmer** [comment]
Yes, or perhaps we should make our RPC response match ethers? I think ethers matches the RPC response from `geth`, right? Either way, we should probably create a proposal and a decision here asap. cc @sanderpick

**Comment by sanderpick** [comment]
The CLI currently spits this out when you create a table:

```
{
  "tableId": "3",
  "prefix": "hello",
  "chainId": 31337,
  "txnHash": "0x826f3ae57d773fe5f0be88ff35d640ce3e8cbae0043f946ddbbfc33d484d17fa",
  "blockNumber": 1441,
  "name": "hello_31337_3"
}
```

when you write to a table, it's returning:

```
{
  "hash": "0x6c0ea4d7e6003c2e7a8e91ed8726ade6f63feed941e304fad72c219c7760be2d"
}
```

not sure where those values are coming from

**Comment by carsonfarmer** [comment]
The "hash" key comes from the RPC API, the create table response is actually created in the SDK, but the key names were a poor choice (mine) I think (https://github.com/tablelandnetwork/js-tableland/blob/main/src/lib/create.ts#L40). They should probably just have transparently pulled in `transactionHash`. TL;DR, we should probably just use `transactionHash` (or on the GO/JSON side `transaction_hash`) everywhere? cc @brunocalza

**Comment by brunocalza** [comment]
Actually, this is the reply for `RelayWriteQuery` and `SetController` calls

```json
{
  "tx": {
    "hash": "0xadc767d2ef88522e5fb85b249f0079f82829f3928edcde46eada8fa65b8ed528"
  }
}
```

It's not simply: 

```json
{
   "hash": "0xadc767d2ef88522e5fb85b249f0079f82829f3928edcde46eada8fa65b8ed528"
}
```
[(maybe SDK is removing the `tx`?)](https://github.com/tablelandnetwork/js-tableland/blob/99eb4d3245773504b97f3635275a611813299cd2/src/lib/tableland-calls.ts#L155)

So the RPC call already gives enough context to know that the hash comes from a transaction. It happened to be that way because we thought we might need more info about the `tx`.

**Comment by carsonfarmer** [comment]
Yeh this part is known, we _were_ stripping it out. Now that I think about it, I think the suggestion of @joewagner above is simply to map `tx.hash` to `transactionHash` to have some continuity with ethers js. I think this is a good suggestion.

**Comment by carsonfarmer** [comment]
I'm going to create a TPD/Discussion for the topic of API names and field names. This issue is really about adding etherscan links, so I'll leave any further discussion about names etc outside of this ticket.
