### ISSUE TITLE
read command requires specifying a chain to query mainnet tables

### ISSUE THREAD

**Issue by datadanne** [tablelandnetwork/js-tableland-cli#212]
Using the latest version
```bash
$ tableland --version
4.0.4
```
It doesn't work to query a table from a non-testnet chain
```
$ tableland read "select * from rig_attributes_42161_15 limit 1"
running read statement: executing read-query: parsing result to json: executing query: no such table: rig_attributes_42161_15
```
Unless a mainnet chain is specified (doesn't have to be the chain that the table lives on, any mainnet chain works)
```
$ tableland read "select * from rig_attributes_42161_15 limit 1" --chain mainnet
{
  meta: { duration: 751.7410420179367 },
  success: true,
  results: [
    {
      display_type: 'string',
      rig_id: 1,
      trait_type: 'VIN',
      value: 'e9e7caceadc2e5fb4fcbd42c0a6ed0097c709aa01888f70e6d924439ec119ca3'
    }
  ]
}
```
 Feels a bit unintuitive to me and I think this is a regression/undocumented change from the v3 cli? I would expect it to either infer that from the tablenames or that I would have to specify the tableland network I want to target, like `--network testnets` to be consistent with the validator api

**Comment by joewagner** [comment]
@datadanne Thanks for reporting this!  I agree that this is counter intuitive. The reason the testnets work, is because there is a default value for the `chain` param, i.e. "maticmum".  
We can determine the correct network to read from using the query statement, but we will have to change the default behaviour.
I'll create a potential solution PR and we can discuss the implementation details there.
